# Generated by Django 3.2.3 on 2021-06-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210617_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сustomization',
            new_name='Customization',
        ),
    ]
